pull_request_rules:
  - name: Automatic merge
    description: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: squash
