[package]
name = "fmu_rs"
version = "0.1.0"
authors = ["ralf"]
edition = "2021"
repository = "https://github.com/avrabe/fmu-rs.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
rust-ini = "0.18"
tracing = "0.1.31"
tracing-subscriber = "0.3.9"
hawkbit = { version = "0.6.0", features= ["hash-digest", "hash-md5", "hash-sha1", "hash-sha256"]}
#hawkbit = {git = "https://github.com/avrabe/hawkbit-rs", branch = "metadata_support", features= ["hash-digest", "hash-md5", "hash-sha1", "hash-sha256"]}
tokio = {version="1.16.1", features= ["full"]}
serde = "1.0.136"
serde_json = "1.0.78"
libc = "0.2.118"
ostree = { version = "0.13.6", features = ["v2021_2"]}
openat = "0.1.21"
rustbus = "0.17.0"

[dev-dependencies]
tempdir = "0.3.7"
