[package]
name = "fmu_rs"
version = "0.1.0"
authors = ["ralf"]
edition = "2021"
repository = "https://github.com/avrabe/fmu-rs.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version="4.0.10", features = ["derive"]}
rust-ini = "0.18.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
hawkbit = { version = "0.6.0", features= ["hash-digest", "hash-md5", "hash-sha1", "hash-sha256"]}
#hawkbit = {git = "https://github.com/avrabe/hawkbit-rs", branch = "metadata_support", features= ["hash-digest", "hash-md5", "hash-sha1", "hash-sha256"]}
tokio = {version="1.19.2", features= ["full"]}
serde = "1.0.145"
serde_json = "1.0.85"
libc = "0.2.134"
ostree = { version = "0.15.0", features = ["v2021_2"]}
openat = "0.1.21"
rustbus = "0.18.0"

[dev-dependencies]
tempdir = "0.3.7"
