[package]
name = "fmu_rs"
version = "0.1.0"
authors = ["ralf"]
edition = "2018"
repository = "https://github.com/avrabe/fmu-rs.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
rust-ini = "0.17"
log = "0.4"
hawkbit = { version = "0.3.0", features= ["hash-digest", "hash-md5", "hash-sha1", "hash-sha256"]}
tokio = {version="1.6.0", features= ["full"]}
serde = "1.0.126"
ostree = { version = "0.11.0", features = ["dox"]}
libc = "0.2.92"
gio = "0.9.1"


