[package]
name = "fmu_rs"
version = "0.1.0"
authors = ["ralf"]
edition = "2018"
repository = "https://github.com/avrabe/fmu-rs.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
rust-ini = "0.17"
tracing = "0.1.29"
tracing-subscriber = "0.3.0"
hawkbit = { version = "0.6.0", features= ["hash-digest", "hash-md5", "hash-sha1", "hash-sha256"]}
#hawkbit = {git = "https://github.com/avrabe/hawkbit-rs", branch = "metadata_support", features= ["hash-digest", "hash-md5", "hash-sha1", "hash-sha256"]}
tokio = {version="1.12.0", features= ["full"]}
serde = "1.0.130"
serde_json = "1.0.68"
libc = "0.2.104"
ostree = { version = "0.13.3", features = ["v2021_2"]}
openat = "0.1.21"
rustbus = "0.17.0"