name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config dh-autoreconf libglib2.0-dev bison liblzma-dev libext2fs-dev libgpgme-dev libfuse-dev
          git clone --depth 1 --branch v2022.1 https://github.com/ostreedev/ostree.git
          cd ostree 
          git submodule update --init
          env NOCONFIGURE=1 ./autogen.sh
          ./configure --without-gpgme --prefix=/usr/
          make -j 20
          sudo make install
          cd ..
          rm -rf ostree
          cargo clippy -- -D warnings

  build-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config dh-autoreconf libglib2.0-dev bison liblzma-dev libext2fs-dev libgpgme-dev libfuse-dev
          git clone --depth 1 --branch v2022.1  https://github.com/ostreedev/ostree.git
          cd ostree 
          git submodule update --init
          env NOCONFIGURE=1 ./autogen.sh
          ./configure --without-gpgme --prefix=/usr/
          make -j 40
          sudo make install
          cd ..
          rm -rf ostree
          cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  create-bitbake:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: prepare for update bitbake
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install kas
          sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm zstd cpio lz4         
      - name: Checkout meta-fmu
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          repository: avrabe/meta-fmu
          path: meta-fmu
      - name: update the SRCREV recipe file
        run:  |
          commit_hash=$(git rev-parse HEAD)
          echo "SRCREV = \"$commit_hash\"" >  meta-fmu/recipes-application/fmu/fmu-rs-srcrev.inc
      - name: update the CREATES recipe file
        run:  |
          cd meta-fmu
          KAS_TARGET=fmu-rs KAS_TASK=update_crates kas build fmu-project.yml
      - name: Commit all changes
        run:  |
          cd meta-fmu
          git config user.name 'fmubot'
          git config user.email 'fmubot@users.noreply.github.com'
          git add -A
          git commit -m "Add new revision"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
           token:  ${{ secrets.PUSH_TOKEN }}
           delete-branch: true
           path: meta-fmu

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  codecov-check:
    name: codecov-check
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install ostree from source (same version as specified in Cargo.toml)
        run: | 
          curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
          apt-get update
          apt-get install -y build-essential pkg-config dh-autoreconf libglib2.0-dev bison liblzma-dev libext2fs-dev libgpgme-dev libfuse-dev
          git clone --depth 1 --branch v2022.1  https://github.com/ostreedev/ostree.git ostree
          cd ostree
          git submodule update --init
          env NOCONFIGURE=1 ./autogen.sh
          ./configure --without-gpgme --prefix=/usr/
          make -j 40
          make install
          cd ..
          rm -rf ostree
      - name: Run tarpaulin
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
  
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
  
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: cobertura.xml
